### ISSUE TITLE
DAC 3 Digit Sector codes?

### ISSUE THREAD

**Issue by danmackenzie** [younginnovations/aidstream-old#108] opened 2015-07-23 16:14 UTC
It has been raised by Tim Barker at HelpAge International that AidStream does not allow for the input of the DAC 3 Digit codes. Is this something that will be changed in v2.01 or the old version?

He has found the the DAC 5 Digit does not work for mapping their work. Other NGOs have said similar things.

**Comment by anjesh** [comment] 2015-11-05 17:20
Duplicate of https://github.com/younginnovations/aidstream/issues/76 
Closing this. Further discussion there.

**Closed as completed by anjesh** 2015-11-05 17:20 UTC
